### ISSUE TITLE
viewing overall results on the main map

### ISSUE THREAD

**Issue by farzad1132** [farzad1132/NetPlanner#12]

**Comment by Pitclair** [comment]
didn't put numbers beside lines, took too much space

![mappopup](https://user-images.githubusercontent.com/46372775/75632516-04ec8e80-5c12-11ea-82fc-bde21106e102.png)

**Comment by Pitclair** [comment]
map legend (early version) 
![image](https://user-images.githubusercontent.com/46372775/75632615-1a15ed00-5c13-11ea-8948-2b1c98c88130.png)

**Comment by Pitclair** [comment]
fixed the legend (added more css styling)
the application now shows the line number ( hover on the lines to get the number just below them)

![image](https://user-images.githubusercontent.com/46372775/76152705-d9691880-60d7-11ea-9919-14bf7631489e.png)

**Comment by farzad1132** [comment]
> fixed the legend (added more CSS styling)
> the application now shows the line number ( hover on the lines to get the number just below them)
> 
> ![image](https://user-images.githubusercontent.com/46372775/76152705-d9691880-60d7-11ea-9919-14bf7631489e.png)

well done
just two things, you didn't change filled and not filled lambdas color? and where is the code? ( create a function that receives a list of lambdas and click event to popup a window and also another function for showing legend ) 
**just show filled lambdas in black color**
