### ISSUE TITLE
creating grooming window

### ISSUE THREAD

**Issue by farzad1132** [farzad1132/NetPlanner#15]

**Comment by farzad1132** [comment]
@nimanaderi , @nimanaderi  push updates on this issue

**Comment by neemes** [comment]
itial file has been pushed. check it in next update we will have stylesheet

**Comment by farzad1132** [comment]
I'm still waiting !!!

**Comment by neemes** [comment]
check boxes added according to MHAzad messages. 
my suggestion is to use pop up window when checkboxes are selected to have setting view 
if agreed tell me to add before 12 pm

**Comment by farzad1132** [comment]
@mhazad99 finish this yourself with the same structure as we talked
