### ISSUE TITLE
Notification bubble is too small

### ISSUE THREAD

**Issue by farzad1132** [farzad1132/NetPlanner#17]
![normal_notified_nodes](https://user-images.githubusercontent.com/47427690/75608951-772d7800-5b19-11ea-83a7-7197da2d5943.PNG)
@mhazad99 make them bigger

**Comment by mhazad99** [comment]
Done!

**Comment by farzad1132** [comment]
> Done!

it's not done.
original icon has got smaller
![icons_2](https://user-images.githubusercontent.com/47427690/75875167-6ede8100-5e28-11ea-91c9-457a839effe7.PNG)

**Comment by mhazad99** [comment]
new change applied

**Comment by farzad1132** [comment]
you actually made original icons smaller to fit with notifications version :))
