### ISSUE TITLE
redesigning panels with layout

### ISSUE THREAD

**Issue by farzad1132** [farzad1132/NetPlanner#21]
this issue is related to #20 
in the current version of panels, items have fixed size and location, but you need to redesign these panels with a layout. ( dynamic resizing )
also, you have to make them prettier
beside current panels, you have to design new panels too

@ShervinSadeghvand start working with QtDesigner.

**wait for further instructions**

**Comment by neemes** [comment]
sizes are the same? and list the new cards

**Comment by neemes** [comment]
some UI's are ready waiting for Shervin for designing last UI. check ui I will create .py files after I get your feedback

**Comment by farzad1132** [comment]
> some UI's are ready waiting for Shervin for designing the last UI. check UI I will create .py files after I get your feedback

- Panels Vertically Cant Resize
- delete old and unused files from panels folder
- be careful about changes that you made on .py files ( you have created a new one for each panel )
- delete **panels for SW** folder
- delete **sockets** folder ( add all the files that you need to their folder )

### **keep directory clean, keep everything organized, it's messy now !!**

**Comment by neemes** [comment]
you said there is no need for vertical resizing so I didn't pay too much attention on what happens while panels are stretching vertically .
after creation of python files folders will be cleaned

**Comment by farzad1132** [comment]
> you said there is no need for vertical resizing so I didn't pay too much attention on what happens while panels are stretching vertically .
> after creation of python files folders will be cleaned

No, I said the opposite of this

**Comment by ShervinSadeghvand** [comment]
I pushed New TP1H UI design in <demandmap_resizable branch\TP1H_Demand\TP1H_Redesigning>
@farzad1132 if its ok move this from In Progress To Done

**Comment by farzad1132** [comment]
> I pushed New TP1H UI design in <demandmap_resizable branch\TP1H_Demand\TP1H_Redesigning>
> @farzad1132 if its ok move this from In Progress To Done

It's not done yet, we have plenty of work to do
@mhazad99 have to use those panels and create a new shelf view

**Comment by farzad1132** [comment]
> you said there is no need for vertical resizing so I didn't pay too much attention on what happens while panels are stretching vertically .
> after creation of python files folders will be cleaned

**clean repository**
I have already mentioned that
