### ISSUE TITLE
creating RWA window

### ISSUE THREAD

**Issue by farzad1132** [farzad1132/NetPlanner#3]
با توجه به توضیحات جلسه یک پنجره که بتونه ورودی های زیر رو از کاربر بگیره رو طراحی کن
[پارامترهای مورد نیاز الگوریتم RWA.docx](https://github.com/farzad1132/NetPlanner/files/4245719/RWA.docx)

**Comment by farzad1132** [comment]
@nimanaderi don't forget to add the stylesheet ( CSS code )

**Comment by neemes** [comment]
.پوش شده است.uiمربوطه درست شده برای ایجاد تغییرات در کد پایتون اگر نکته ای دارید لحاظ کنید فقط فایل ui

**Comment by farzad1132** [comment]
> .پوش شده است.uiمربوطه درست شده برای ایجاد تغییرات در کد پایتون اگر نکته ای دارید لحاظ کنید فقط فایل ui

what about style sheets?

**Comment by farzad1132** [comment]
I can't see any 'ok' or 'apply' button even 'Cancel' button

**Comment by neemes** [comment]
your common style sheet is applied it will be changed due to code and limitions 
ok and cancel push buttons will be apllied   
is there any ideal graphical changes? specially in stylesheet and order of items

**Comment by farzad1132** [comment]
> your common style sheet is applied it will be changed due to code and limitions
> ok and cancel push buttons will be apllied
> is there any ideal graphical changes? specially in stylesheet and order of items

 - add horizontal lines and group related inputs
 - change the window background-color
 - search for some charming ideas for input menus and apply them ( low priority )

**Comment by neemes** [comment]
i did not understand what u mean by hint 1  
ok and cancel button have been applied 
window background color changed

**Comment by farzad1132** [comment]
> i did not understand what u mean by hint 1
> ok and cancel button have been applied
> window background color changed

leave it now, I'll explain it in skype tomorrow
