### ISSUE TITLE
another warning after your splitter code

### ISSUE THREAD

**Issue by farzad1132** [farzad1132/NetPlanner#42]
warning message:
`DirectWrite: CreateFontFaceFromHDC() failed (Indicates an error in an input file such as a font file.) for QFontDef(Family="8514oem", pointsize=7.8, pixelsize=20, styleHint=5, weight=50, stretch=100, hintingPreference=0) LOGFONT("8514oem", lfWidth=0, lfHeight=-20) dpi=120`

**Comment by mhazad99** [comment]
I checked it now and that warning isn't because of me!
I don't get it any time that I run the code.
