### ISSUE TITLE
demand map warnings

### ISSUE THREAD

**Issue by farzad1132** [farzad1132/NetPlanner#6]

**Comment by farzad1132** [comment]
@mhazad99 what the news? 
I don't think this issue be a big deal

**Comment by mhazad99** [comment]
problem solved!

**Comment by farzad1132** [comment]
> problem solved!

wait !!
![mapnames](https://user-images.githubusercontent.com/47427690/75875718-79e5e100-5e29-11ea-9f85-dbd814a72b28.PNG)
make the distance of names and nodes longer
and change names color to get more detectable

**Comment by mhazad99** [comment]
new change applied

**Comment by farzad1132** [comment]
not well but good for now
